stages:
  - plan
  - apply

image:
  name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

variables:
  YC_TOKEN: $YC_TOKEN
  YC_SERVICE_ACCOUNT: $YC_SERVICE_ACCOUNT
  # YC_FOLDER_ID: $YC_FOLDER_ID
  SERVICE_ACCOUNT_KEY: $SERVICE_ACCOUNT_KEY
  ACCESS_KEY: $ACCESS_KEY
  SECRET_KEY: $SECRET_KEY

plan:
  stage: plan
  before_script:
    - cd terraform
    # - terraform init
    - terraform init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY"
    # - terraform state list
    # - terraform state rm yandex_storage_bucket.test
    # - terraform state pull
  script:
    - terraform plan -out="tf.plan" -var 'yc_folder_id=$YC_FOLDER_ID' -var 'yc_id=$YC_CLOUD_ID' -var 'yc_service_account=$YC_SERVICE_ACCOUNT'
  artifacts:
    paths:
      - $CI_PROJECT_DIR/terraform

apply:
  stage: apply
  before_script:
    - cd terraform
  script:
    - terraform init
    - terraform apply -auto-approve "tf.plan"
  when: manual